--- 
    apiVersion: v1
    kind: Service
    metadata: 
      labels: 
        service: reverse-proxy
      name: reverse-proxy-service
    specs: 
      ports: 
        - 
          name: "80:80"
          port: 8080
          targetPort: 8080
      selector: 
        service: reverse-proxy